services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    image: son07/nutriguide-backend:latest
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - app-network

  frontend:
    image: son07/nutriguide-frontend:latest
    restart: always
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
